pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/yourusername/calculator-project.git'
            }
        }
        
        stage('Build') {
            steps {
                sh '''
                    mkdir -p build
                    cd build
                    cmake ..
                    make
                '''
            }
        }
        
        stage('Test') {
            steps {
                sh '''
                    cd build
                    ./test_calculator
                '''
            }
        }
        
        stage('Docker Build') {
            steps {
                sh 'docker build -t calculator:latest -f docker/Dockerfile.dev .'
            }
        }
        
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                sh 'echo "Deploying application..."'
                // Add deployment steps here
            }
        }
    }


    
    post {
        always {
            cleanWs()
        }
    }
}